language: csharp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      mono: latest
      dotnet: 2.0.0

script:
  - dotnet --info
  - dotnet restore
  - dotnet test ./test/FSharp.Data.HList.Tests/FSharp.Data.HList.Tests.fsproj
