language: csharp
sudo: false
env:
  global:
    - CONFIGURATION="Release"
mono:
  - 3.12.0
  - 3.10.0
solution: Data.List.sln
install:
  - nuget install Persimmon.Console -Pre -OutputDirectory packages -ExcludeVersion
script:
  - xbuild ./Data.HList.sln /p:Configuration=${CONFIGURATION}
  - mono --runtime=v4.0 ./packages/Persimmon.Console/tools/Persimmon.Console.exe --parallel ./FSharp.Data.HList.Tests/bin/${CONFIGURATION}/FSharp.Data.HList.Tests.dll

